Repository mulesoft/docs-connectors, pull requests merged in 2020-03, with the labels that each got.

#670 Compression Module Documentation Reference v2.1
  modules/ROOT/pages/compression/compression-documentation.adoc
Labels: DO NOT MERGE UNTIL RELEASED

#658 update metadata for connectors
  modules/ROOT/nav.adoc
  modules/ROOT/pages/aggregator/aggregators-module.adoc
  modules/ROOT/pages/amazon/amazon-s3-connector-reference.adoc
  modules/ROOT/pages/anypoint-mq/3.x/anypoint-mq-connector.adoc
  modules/ROOT/pages/anypoint-mq/3.x/anypoint-mq-publish.adoc
  modules/ROOT/pages/as2/as2-connector-reference.adoc
  modules/ROOT/pages/as2/as2-connectorMule4.adoc
  modules/ROOT/pages/compression/compression-module.adoc
  modules/ROOT/pages/edifact/edifact-edi-connector.adoc
  modules/ROOT/pages/ftp/ftps-connector.adoc
  modules/ROOT/pages/hl7/hl7-connector.adoc
  modules/ROOT/pages/hl7/hl7-mllp-connector.adoc
  modules/ROOT/pages/include_link_list.adoc
  modules/ROOT/pages/java/java-reference.adoc
  modules/ROOT/pages/jms/jms-activemq-configuration.adoc
  modules/ROOT/pages/jms/jms-connector.adoc
  modules/ROOT/pages/jms/jms-consume.adoc
  modules/ROOT/pages/jms/jms-documentation.adoc
  modules/ROOT/pages/jms/jms-xml-ref.adoc
  modules/ROOT/pages/metrics/custom-metrics-connector-reference.adoc
  modules/ROOT/pages/metrics/custom-metrics-connector.adoc
  modules/ROOT/pages/microsoft/microsoft-365-ops-connector.adoc
  modules/ROOT/pages/netsuite/netsuite-connector-reference.adoc
  modules/ROOT/pages/oauth/oauth-documentation.adoc
  modules/ROOT/pages/oauth/oauth2-provider-documentation-reference.adoc
  modules/ROOT/pages/object-store/object-store-connector.adoc
  modules/ROOT/pages/rosettanet/rosettanet-connector-reference.adoc
  modules/ROOT/pages/salesforce/salesforce-connector-reference-100.adoc
  modules/ROOT/pages/salesforce/salesforce-connector-reference-96.adoc
  modules/ROOT/pages/salesforce/salesforce-connector-reference.adoc
  modules/ROOT/pages/sap/sap-s4hana-soap-connector.adoc
  modules/ROOT/pages/servicenow/servicenow-connector-examples.adoc
  modules/ROOT/pages/servicenow/servicenow-connector.adoc
  modules/ROOT/pages/siebel/siebel-connector-reference.adoc
  modules/ROOT/pages/siebel/siebel-connector.adoc
  modules/ROOT/pages/tradacoms/tradacoms-edi-connector.adoc
  modules/ROOT/pages/veevavault/veevavault-connector-reference.adoc
  modules/ROOT/pages/x12-edi/x12-edi-connector.adoc
  modules/ROOT/pages/zuora-aqua/zuora-aqua-connector.adoc
Labels: DO NOT MERGE

#573 Update as2-connectorMule4.adoc
  modules/ROOT/pages/as2/AS2-connector-examples.adoc
  modules/ROOT/pages/as2/AS2-connector-xml-maven.adoc
  modules/ROOT/pages/as2/as2-connector-reference.adoc
  modules/ROOT/pages/as2/as2-connectorMule4.adoc
Labels: Waiting for release to occur

#663 Update sap-s4hana-cloud-connector-reference.adoc
  modules/ROOT/nav.adoc
  modules/ROOT/pages/sap/sap-s4hana-cloud-connector-reference.adoc
  modules/ROOT/pages/sap/sap-s4hana-cloud-connector-upgrade-migrate.adoc
  modules/ROOT/pages/sap/sap-s4hana-cloud-connector.adoc
Labels: Waiting for release to occur
